### ISSUE TITLE
[Linux] - Location feature not working. location()

### ISSUE THREAD

**Issue by ErmanIZTECH** [ErmanIZTECH/mantar_avi#10]
On linux server the bot was unable to handle location() function.
Please see the attached `Traceback`

Traceback (most recent call last):
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/home/mantar/gitHub/https/mantar_avi/man_tarBot.py", line 97, in location
    update.message.reply_photo(photo=open("coordinate_image.png", "rb"))
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/message.py", line 1165, in reply_photo
    return self.bot.send_photo(
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/bot.py", line 732, in send_photo
    return self._message(  # type: ignore[return-value]
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 359, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/mantar/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Image_process_failed

**Comment by ErmanIZTECH** [comment]
The download image button is not working on the page.
